### ISSUE TITLE
c# arithmetic overflow exception

### ISSUE THREAD

**Issue by Baseult** [BIGDummyHead/Dummy-Memory#2]
First of all, thanks for your work.
This is by far better coded than the memory NuGet, this has great potential :).

Using it with 64bit Process and Code Cave, I get an error: "The arithmetic operation has caused an overflow".
Debugging it shows me it is caused at:
"DummyMemory.Memory.<AoB>d__26.MoveNext()"
"System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)"
"DummyMemory.Detouring.Cave..ctor(Memory m, String aobPattern, Byte[] injection, Allocation alloc)"

You probably have to change all int to int64 or long.

**Comment by BIGDummyHead** [comment]
Thank you.

Can you please share a snippet of your code? This would help greatly, thanks.

**Comment by Baseult** [comment]
Sure, I just started using it so I am just testing around.
The code is used for the game "Genshin Impact" and I am trying to create a code cave for the Module "UserAssembly.dll+36652FA". 

Using the aob scan, it wasn't able to find the correct address or nothing at all (Area of byte scan failed), no matter if I added or removed more AOB Bytes. Is it possible to just cave using the direct address with the custom module?

The code I used (sorry formatting code is shitty here":

`private void button1_Click(object sender, EventArgs e)`
`{`
` Memory mem = new Memory("GenshinImpact");`
`string aob = "F2 0F 11 45 E0 48 85 C0";`
`byte[] inject = { 0xF2, 0x0F, 0x10, 0x45, 0xE0};`

`Cave cave = new Cave(mem, aob, inject, new Cave.Allocation` //Error happens here
` {
memorySize = 1000,
  replacementSize = 5
  });
  `

  `cave.Inject();`
`}`

**Comment by BIGDummyHead** [comment]
What is the base for the 'UserAssembly.dll' address?

**Comment by Baseult** [comment]
The range of the UserAssembly.dll is from 7FFF0F630000 to 7FFF1AC51000.
The aob scanner should find "F2 0F 11 45 E0 48 85 C0 0F 84 D6" as it is a unique signature for the address UserAssembly.dll+36652FA, but it gives me "Area of byte scan failed." instead.

**Comment by BIGDummyHead** [comment]
Yea, it is giving that to you since there is 0 IntPtr returned from memory.AoB, but you are right since it is unique it should give it to you, maybe something is messed up with the input you gave it or the CheckPattern method.

**Comment by Baseult** [comment]
Yeah, using the AOB Injection and an external signature maker, I can confirm that the Signature indeed works and is also unique. I guess there is something messed up with the PatternScanner.

![image](https://user-images.githubusercontent.com/45830921/141214756-a0fff550-9240-407e-a7dc-df78fb1549c4.png)
![image](https://user-images.githubusercontent.com/45830921/141214860-0dc9e199-72b5-4d46-84d8-f34a058ecb71.png)

Depending on if you would consider using an external pattern scanner instead, I can recommend you the "Reloaded.Memory" NuGet/library by Sewer56. It is the fastest I've tested so far working reliable at scanning patterns supporting wildcards too.

**Comment by BIGDummyHead** [comment]
Yea I am looking into it, thank you for pointing this out, this issue will be closed when I can get this fixed and you can test this.

**Comment by Baseult** [comment]
Alright, take your time and thanks for your work.

**Comment by BIGDummyHead** [comment]
I really appreciate you again for bringing this to my attention, the library will have an update pushed later tonight that fixes this issue! The problem was that we were starting at the base of the module and ending at the size. So this limited it from expanding outwards to other libraries loaded.

**Comment by BIGDummyHead** [comment]
Ok the push has been made, please close out this issue when you feel satisfied to do so. Cave.cs now has two new constructors. In memory you should see Three different types of AoB scanning and the pattern scanner now allows wildcards as well. |

For the AoB scans


* AoB("F0 00", 0, int.MaxValue) - This method will start scanning from the base of the process to the end of it, this is just like Cheat Engine

* ModuleAoB("F0 00", ProcessModule) - This method will start at the base of the module selected and end at the size of the module

* BaseAoB("F0 00") - This method will use the base address of the Process' main module

Hopefully these methods will help expand this game library and now the cave does not have to be initialized with an AoB scan making things much faster for injecting caves and such.

**Comment by BIGDummyHead** [comment]
Closing for week without response.
