### ISSUE TITLE
error

### ISSUE THREAD

**Issue by barry-mcockiner** [BIGDummyHead/Dummy-Memory#3]
![image](https://user-images.githubusercontent.com/95534062/171970638-e2bfb37b-e662-4c78-999e-8a3410e8c765.png)
it does not work for injector

**Comment by barry-mcockiner** [comment]
says the class types are not found

**Comment by BIGDummyHead** [comment]
Please make sure you are using the correct version.

https://github.com/BIGDummyHead/Dummy-Memory/releases/tag/1.0.0.0.1
